name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 wheel

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: <TON_PROJET_SONARCLOUD>
          SONAR_ORGANIZATION: <TON_ORGANISATION>

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Python package artifact
        uses: actions/upload-artifact@v3
        with:
          name: elt-python-package
          path: dist/*.whl

      - name: Build Docker image
        run: |
          docker build -t elt-project .

      - name: Push Docker image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag elt-project ghcr.io/${{ github.repository_owner }}/elt-project:latest
          docker push ghcr.io/${{ github.repository_owner }}/elt-project:latest
